networks:
  dev:

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend:/backend
      - model_cache:/root/.cache
    environment:
      - REDIS_HOST=redis
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"

    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    networks:
      - dev


volumes:
  model_cache:
